// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: importserials.sql

package importserials

import (
	"context"
	"database/sql"
)

const listSerialsByPallet = `-- name: ListSerialsByPallet :many
SELECT
  a.id, a.pallet, a.masterbox, a.serial_number, a.part_number, a.created_at
FROM
  import_pallets_serials a
WHERE a.pallet = ?
ORDER BY a.pallet ASC, a.created_at DESC
`

func (q *Queries) ListSerialsByPallet(ctx context.Context, pallet sql.NullString) ([]ImportPalletsSerial, error) {
	rows, err := q.db.QueryContext(ctx, listSerialsByPallet, pallet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportPalletsSerial
	for rows.Next() {
		var i ImportPalletsSerial
		if err := rows.Scan(
			&i.ID,
			&i.Pallet,
			&i.Masterbox,
			&i.SerialNumber,
			&i.PartNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
