// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package importserials

import (
	"database/sql"
	"time"
)

type ImportPalletsSerial struct {
	ID           int32
	Pallet       sql.NullString
	Masterbox    sql.NullString
	SerialNumber sql.NullString
	PartNumber   sql.NullString
	CreatedAt    time.Time
}
