// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package importserials

import (
	"database/sql"
)

type ImportPalletsSerial struct {
	Pallet       sql.NullString
	Masterbox    sql.NullString
	SerialNumber sql.NullString
	PartNumber   sql.NullString
	Uuid         sql.NullString
}
