// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: labels.sql

package labels

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :execresult
INSERT IGNORE INTO labels () VALUES ()
`

func (q *Queries) Create(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, create)
}

const deleteByID = `-- name: DeleteByID :exec
INSERT INTO labels_deletes (id) VALUES (?)
`

func (q *Queries) DeleteByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteByID, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT
  labels_data.id, labels_data.customer, labels_data.model, labels_data.part_number, labels_data.station, labels_data.dpi, labels_data.label, labels_data.sql_queries, labels_data.author, labels_data.created_at
FROM
  labels_data
  LEFT JOIN labels_deletes ON labels_data.id = labels_deletes.id
WHERE labels_deletes.id IS NULL
  AND labels_data.id = ?
ORDER BY labels_data.created_at DESC
LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id int32) (LabelsDatum, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i LabelsDatum
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Model,
		&i.PartNumber,
		&i.Station,
		&i.Dpi,
		&i.Label,
		&i.SqlQueries,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const listPaginate = `-- name: ListPaginate :many
SELECT
  labels_data.id, labels_data.customer, labels_data.model, labels_data.part_number, labels_data.station, labels_data.dpi, labels_data.label, labels_data.sql_queries, labels_data.author, labels_data.created_at
FROM
  labels_data
  LEFT JOIN labels_deletes ON labels_data.id = labels_deletes.id
WHERE labels_deletes.id IS NULL
  AND labels_data.created_at IN(
    SELECT MAX(labels_data.created_at)
    FROM labels_data
    GROUP BY labels_data.id
  )
ORDER BY labels_data.created_at DESC
LIMIT ? OFFSET ?
`

type ListPaginateParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPaginate(ctx context.Context, arg ListPaginateParams) ([]LabelsDatum, error) {
	rows, err := q.db.QueryContext(ctx, listPaginate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabelsDatum
	for rows.Next() {
		var i LabelsDatum
		if err := rows.Scan(
			&i.ID,
			&i.Customer,
			&i.Model,
			&i.PartNumber,
			&i.Station,
			&i.Dpi,
			&i.Label,
			&i.SqlQueries,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :execresult
INSERT INTO labels_data (id, customer, model, part_number, station, dpi, label, sql_queries, author)
  VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpdateParams struct {
	ID         int32
	Customer   string
	Model      string
	PartNumber string
	Station    string
	Dpi        int32
	Label      string
	SqlQueries string
	Author     string
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, update,
		arg.ID,
		arg.Customer,
		arg.Model,
		arg.PartNumber,
		arg.Station,
		arg.Dpi,
		arg.Label,
		arg.SqlQueries,
		arg.Author,
	)
}
