// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: labels.sql

package labels

import (
	"context"
)

const createLabel = `-- name: CreateLabel :exec
INSERT IGNORE INTO labels (uuid) VALUES (uuid())
`

func (q *Queries) CreateLabel(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createLabel)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
INSERT INTO labels_deletes (uuid) VALUES (?)
`

func (q *Queries) DeleteLabel(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteLabel, uuid)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT
  labels_data.uuid, labels_data.customer, labels_data.family, labels_data.model, labels_data.part_number, labels_data.station, labels_data.label, labels_data.created_at
FROM
  labels_data
  INNER JOIN labels ON labels_data.uuid = labels.uuid
  LEFT JOIN labels_deletes on labels.uuid = labels_deletes.uuid
WHERE labels_deletes.uuid IS NULL
ORDER BY labels_data.created_at DESC
LIMIT 1
`

func (q *Queries) GetLabel(ctx context.Context) (LabelsDatum, error) {
	row := q.db.QueryRowContext(ctx, getLabel)
	var i LabelsDatum
	err := row.Scan(
		&i.Uuid,
		&i.Customer,
		&i.Family,
		&i.Model,
		&i.PartNumber,
		&i.Station,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const updateLabel = `-- name: UpdateLabel :exec
INSERT INTO labels_data (uuid, customer, family, model, part_number, station, label)
  VALUES(?, ?, ?, ?, ?, ?, ?)
`

type UpdateLabelParams struct {
	Uuid       string
	Customer   string
	Family     string
	Model      string
	PartNumber string
	Station    string
	Label      string
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) error {
	_, err := q.db.ExecContext(ctx, updateLabel,
		arg.Uuid,
		arg.Customer,
		arg.Family,
		arg.Model,
		arg.PartNumber,
		arg.Station,
		arg.Label,
	)
	return err
}
