// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package labels

import (
	"database/sql"
)

type Label struct {
	Uuid      string
	CreatedAt sql.NullTime
}

type LabelsDatum struct {
	Uuid       string
	Customer   string
	Family     string
	Model      string
	PartNumber string
	Station    string
	Label      string
	CreatedAt  sql.NullTime
}

type LabelsDelete struct {
	Uuid      string
	CreatedAt sql.NullTime
}
