// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package labels

import (
	"time"
)

type Label struct {
	ID        int32
	CreatedAt time.Time
}

type LabelsDatum struct {
	ID         int32
	Name       string
	Customer   string
	Model      string
	PartNumber string
	Station    string
	Dpi        int32
	Label      string
	Setup      string
	SqlQueries string
	Author     string
	CreatedAt  time.Time
}

type LabelsDelete struct {
	ID        int32
	CreatedAt time.Time
}
