// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package labels

import (
	"time"
)

type Label struct {
	ID        int32
	CreatedAt time.Time
}

type LabelsDatum struct {
	ID          int32
	Customer    string
	Family      string
	Model       string
	PartNumber  string
	OrderNumber string
	Line        string
	Station     string
	Dpi         int32
	Label       string
	Author      string
	CreatedAt   time.Time
}

type LabelsDelete struct {
	ID        int32
	CreatedAt time.Time
}
