USE dbdev;

CREATE TABLE labels (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE labels_data (
    id INT NOT NULL,
    customer VARCHAR(32) NOT NULL,
    family VARCHAR(8) NOT NULL,
    model VARCHAR(16) NOT NULL,
    part_number VARCHAR(16) NOT NULL,
    station VARCHAR(32) NOT NULL,
    label TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES labels(id)
);

CREATE TABLE labels_deletes (
    id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES labels(id)
);
